### PR TITLE
Don't encode sent message if it is of type bytes

### PR DESCRIPTION
**Pull request by yehonatanz**

### CODE REVIEW

**Comment by mlasevich** [comment]
Thanks for the contribution.

I am trying to understand the use-case -  under what scenario would it be already encoded as JSON but not be a string? 

I mean, if you do not wish to encode, you can just disable the encode altogether - this check is primarily intended to avoid accidentally double encoding - is there case where it is encoded to json but not a string?

**Comment by yehonatanz** [comment]
This is intended to allow users to encode their messages themselves, including non JSON messages.
Non-JSON messages usually encode to raw bytes, which redis supports nicely.

According to the line I modified a `bytes` message will always satisfy `not isinstance(message, str)` and thus will always get encoded, which is not what one would expect when supplying raw bytes.
Perhaps I'm missing something, how does one disable encoding altogether?

**Comment by mlasevich** [comment]
Oh, I got it. It makes sense, though my preference would be to change `encode`  parameter to be tristate (True/False/None) instead of true/false and only autodetect if it is None - it would give more control to user - though it would be a breaking change :-/ ...

**Comment by yehonatanz** [comment]
I agree about the parameter, but it seems to me that even in autodetect mode, `bytes` shouldn't get encoded, so that PR is still relevant.

**Comment by mlasevich** [comment]
> I agree about the parameter, but it seems to me that even in autodetect mode, `bytes` shouldn't get encoded, so that PR is still relevant.

I can live with that

**Pull request merged**
